name: Check Directly Contents

on: [push]

jobs:
    deploy-book:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
  
      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  
      # PATH to Poetry
      - name: Add path for Poetry
        # run: echo "::add-path::$HOME/.poetry/bin"
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
  
      # Install Dependencies
      - name: Install Dependencies
        run: poetry install --no-interaction
  
      - name: Check Directly
        run: poetry run python check_path.py
