name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
  pull_request:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # Install Poetry
    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

    # PATH to Poetry
    - name: Add path for Poetry
      run: echo "::add-path::$HOME/.poetry/bin"

    # Install Dependencies
    - name: Install Dependencies
      run: poetry install --no-interaction

    # Build the book
    - name: Build the book
      run: |
        poetry run jupyter-book build bookShelf/

    # Push the book's HTML to github-pages
    - name: Push _build/html to gh-pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./bookShelf/_build/html